### ISSUE TITLE
Erro na validação

### ISSUE THREAD

**Issue by bozoh** [danielfariati/cpf-cnpj-validator#1]
O código não leva em consideração os cpf/cnpj com todos os números iguais, com exceção do 00000000000.
Então  11111111111, 22222222222, ....  99999999999  são considerados válidos

**Comment by danielfariati** [comment]
Olá!
Eu não estou mais dando manutenção no projeto.
Não recomendo utilizá-lo, de qualquer maneira, pois está bastante desatualizado, já que fazem mais de 5 anos que não mexo nele.
Se quiser, sinta-se livre para abrir um _pull-request_ corrigindo o problema, que eu valido e realizo o _merge_.

Dito isso, sugiro que utilize o https://github.com/caelum/caelum-stella no lugar.
